import { Text } from '@asyncapi/generator-react-sdk';

export default function CodegenComment() {
  return (
    <Text newLines={2}>
      {`/// <summary>
/// Generated by the AsyncAPI Generator. DO NOT EDIT!
/// </summary>`}
    </Text>
  );
}
